### PR TITLE
Handle correctly plural form, even if single plural form.

### LINKED ISSUE #33: ngettext fails on with substitutions with nplurals=1
We started using this gettext implementation recently, and it did everything we wanted to until we tried adding a language with a single plural form. Big thanks to @guillaumepotier 👏 

Our source language is English with nplurals=2, our source po file contains

```
msgid "You only have %1 lesson left to finish %2."
msgid_plural "You only have %1 lessons left to finish %2."
msgstr[0] ""
msgstr[1] ""
```

We use Transifex to translate that into Tetum which gives us back a po file like this

```
"Plural-Forms: nplurals=1; plural=0;\n"

msgid "You only have %1 lesson left to finish %2."
msgid_plural "You only have %1 lessons left to finish %2."
msgstr[0] "Ita hela deit lisaun %1 atu remata %2."
```
Note the lack of a `msgstr[1]`

This results ( po2json ) in a json file looking like this
```
    "": {
        "language": "tet",
        "plural-forms": "nplurals=1; plural=0;"
    },
    "You only have %1 lesson left to finish %2.": [
        "Ita hela deit lisaun %1 atu remata %2."
    ],
```

And this results in 
```
                ngettext(
                    "You only have %1 lesson left to finish %2.",
                    "You only have %1 lessons left to finish %2.",
                    5,
                    "title"
                );
```
giving us `Ita hela deit lisaun title atu remata undefined`

I have hacked a solution where i just pad the single length arrays in the parsed json object, and I may be able to bypass that by getting transifex to correctly reference Tetum as a nplurals=2 language.

In case this represents a bug I got as far as a fork with a failing test, but no farther in the time allowed https://github.com/PeteCoward/gettext.js/tree/plurals1_behaviour

### PR DESCRIPTION
**Pull request by guillaumepotier**
Should fix #33

### CODE REVIEW

File: tests/tests.js [hunk 1]
```diff
@@ -250,6 +250,23 @@
...
+                    i18n.setMessages('messages', 'tdt', {
+                        "%1 lesson left in %2.":
+                        [
+                            "%1 lisaun iha %2"
+                        ],
+                        "%1 lesson left.": [
+                            "%1 lisaun iha."
+                        ]
+                    }, 'nplurals=1; plural=0;');
+                    console.log('here');
```
Comment (PeteCoward) [inline tests/tests.js:264]:
```suggestion
```

**Comment by guillaumepotier** [comment]
@PeteCoward that's a pretty neat CR ;) Thanks!

I'll remove this rogue `console.log` and push/publish the new version today.

Keep you posted

Best
